default: &default
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 5
  username: raffle_bee
  password:
  host: localhost

development:
  <<: *default
  database: raffle_bee_development

test:
  <<: *default
  database: raffle_bee_test

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>
